title: QuenTine 的空间
subtitle: 攻略、笔记及其他
description: 通过写教程学习
baseurl: ""
url: "https://quentine.me"
enforce_ssl: "quentine.me"
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
date_format: "ordinal"
keywords: code, blog, fun

author: QuenTine
email: qt911025@163.com
github_username:  qt911025
repository: qt911025/qt911025.github.io

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
parmalink: /:year/:month/:day/:title/
gems:
  - jekyll-github-metadata
  - rouge
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
sass:
  sass_dir: _sass
exclude:
  - Gemfile
  - Gemfile.lock

subscribe_rss: /feed.xml

netease_gentie_key: e72ddc6ba6c242798aa97a4856d62c29
google:
  analytics_id: UA-98448525-1
